[package]
authors = ["Sean Leffler <sean@errno.com>"]
description = "A resilient, distributed version control system based on Git and designed for use with extremely large repositories."
name = "attaca"
version = "0.1.0"

[dependencies]
clap = "2.28.0"
failure = "0.1.0"
failure_derive = "0.1.1"

[workspace]
members = [
    "attaca-core",
    "attaca-api",
]
