[package]
authors = ["Sean Leffler <sean@errno.com>"]
description = "A resilient, distributed version control system based on Git and designed for use with extremely large repositories."
name = "attaca"
version = "0.1.0"

[[bin]]
doc = false
name = "attaca"
path = "src/bin/main.rs"
required-features = ["binaries"]

[dependencies]
bincode = "0.8.0"
digest = "0.6.2"
digest-writer = "0.2.0"
error-chain = "0.11.0"
futures = "0.1.16"
futures-bufio = "0.2.0"
futures-cpupool = "0.1.6"
histogram = "0.6.7"
indicatif = "0.7.0"
memmap = "0.5.2"
owning_ref = "0.3.3"
quickcheck = "0.4.1"
rad = "0.3.3"
seahash = "3.0.5"
serde = "1.0.11"
serde_derive = "1.0.11"
sha3 = "0.6.0"
slog = "2.0.6"
toml = "0.4.4"
typenum = "1.9.0"
void = "1.0.2"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dependencies.clap]
optional = true
version = "2.26.0"

[dependencies.generic-array]
features = ["serde"]
version = "0.8.2"

[features]
binaries = ["clap"]
default = ["dev"]
dev = ["binaries"]
max_level_trace = ["slog/max_level_trace"]

[lib]
name = "attaca"
path = "src/lib.rs"
