[package]
authors = ["Sean Leffler <sean@errno.com>"]
description = "A resilient, distributed version control system based on Git and designed for use with extremely large repositories."
name = "attaca"
version = "0.1.0"

[[bin]]
doc = false
name = "attaca"
path = "src/bin/main.rs"
required-features = ["binaries"]

[dependencies]
bincode = "0.8.0"
digest = "0.6.2"
digest-writer = "0.2.0"
error-chain = "0.11.0"
futures = "0.1.16"
futures-bufio = "0.2.0"
futures-cpupool = "0.1.6"
histogram = "0.6.7"
itertools = "0.6.3"
lazy_static = "0.2.8"
libc = "0.2.29"
memmap = "0.5.2"
quickcheck = "0.4.1"
rad = "0.5.0"
seahash = "3.0.5"
serde = "1.0.11"
serde_derive = "1.0.11"
sha3 = "0.6.0"
slog = "2.0.6"
stable_deref_trait = "1.0.0"
toml = "0.4.4"
typenum = "1.9.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dependencies.clap]
optional = true
version = "2.26.0"

[dependencies.futures-await]
git = "https://github.com/alexcrichton/futures-await"

[dependencies.generic-array]
features = ["serde"]
version = "0.8.2"

[dependencies.indicatif]
git = "https://github.com/sdleffler/indicatif"
optional = false

[dependencies.owning_ref]
git = "https://github.com/sdleffler/owning-ref-rs"

[dependencies.qp-trie]
features = ["serde"]
version = "0.7.1"

[features]
binaries = ["clap"]
default = ["dev"]
dev = ["binaries"]
max_level_trace = ["slog/max_level_trace"]

[lib]
name = "attaca"
path = "src/lib.rs"
