[package]
authors = ["Sean Leffler <sean@errno.com>"]
name = "attaca-client"
version = "0.1.0"

[dependencies]
clap = "~2.29.3"
failure = "0.1.1"
histogram = "0.6.8"
iter-read = "0.1.0"
rand = "0.4.2"

[dependencies.attaca]
path = ".."
